logging:
  version: 1
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    stderr:
      class: logging.StreamHandler
      formatter: standard
      level: DEBUG
      stream: ext://sys.stderr
  loggers:
    telethon:
      handlers: [stderr]
      level: WARN
    tg_sync:
      handlers: [stderr]
      level: INFO

pipeline:
- filters:
  - chat_id: -623956442
  actions:
  - action: set
    chat_name: Семейство
    save_media: true
- filters:
  - chat_id: 213080381
  actions:
  - action: set
    chat_name: Катя
    save_media: true
- filters:
  - chat_id: 512494047
  actions:
  - action: log

- filters:
  - save_media: true
    type_id: [photo, video, document]
  actions:
  # - action: log
  - action: save
    old_save_path: "../Telegram/{date_utc:%Y}/{chat_name}/{date_utc:%Y%m%d-%H%M%S}-{type_id}-{message_id}{file_ext}"
    save_path: "../Telegram/{date:%Y}/{chat_name}/{date:%Y%m%d-%H%M%S}-{message_id}{file_ext}"
    skip_existing: true
